from tkinter import *
root=Tk()
root.title('Login Credential')
def get_info():
    l3=Label(text=f'The entered username is {username.get()}')
    l3.grid()
    print(f'The entered username is {username.get()}')
    print(f'The entered Password is {password.get()}')
root.geometry('430x350')
l1=Label(root,text='Username:',font='calibri 16 bold')
l1.grid()
l2=Label(root,text='Password:',font='calibri 16 bold')
l2.grid(row=1)
username=StringVar()
password=StringVar()
userentry=Entry(root,textvariable=username)
userentry.grid(row=0,column=1)
passentry=Entry(root,textvariable=password)
passentry.grid(row=1,column=1)
b1=Button(root,text='Submit',command=get_info)
b1.grid(row=2,column=0)
root.mainloop()